import type { Metadata } from 'next'
import './globals.css'
import { Roboto } from 'next/font/google'
import Menu from './Menu'

const roboto = Roboto({
    subsets: ['latin'],
    weight: ['400', '700'],
})

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${roboto.className} h-screen flex`}>
                <Menu />
                {children}
            </body>
        </html>
    )
}
